name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php:
          - 8.4
        stability:
          - prefer-stable
          - prefer-lowest

    name: "Run Tests: ${{ matrix.os }} - PHP ${{ matrix.php }} - ${{ matrix.stability }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - if: matrix.os == 'ubuntu-latest' && matrix.stability == 'prefer-stable'
        name: Execute tests with coverage
        run: vendor/bin/phpunit --coverage-clover build/reports/clover.xml

      - if: matrix.os != 'ubuntu-latest' || matrix.stability != 'prefer-stable'
        name: Execute tests
        run: vendor/bin/phpunit --coverage-clover build/reports/clover.xml

      # Only upload coverage once.
      - if: matrix.os == 'ubuntu-latest' && matrix.stability == 'prefer-stable'
        name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          file: build/reports/clover.xml